### ISSUE TITLE
Standardize feature categories

### ISSUE THREAD

**Issue by cmndrsn** [tuomaseerola/metaMER#2]
Some studies use different features that don't line up exactly with Panda (2021):
 
These often include lower-level features classified by the authors as "temporal" or "spectral".

For example, AMG1608, which uses features from MIRToolbox and YAAFE includes four categories (Tonal, Temporal, Spectral, MFCC):
https://github.com/tuomaseerola/metaMER/blob/main/etc/image.png

**Comment by tuomaseerola** [comment]
We now have a solution for this in preprocessing
